name: transcrypt
description: "End-to-End encrypted cross-platform file sharing application."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  network_info_plus: ^7.0.0
  http: ^1.5.0
  path_provider: ^2.1.5
  flutter_dotenv: ^6.0.0
  file_picker: ^8.0.0
  permission_handler: ^12.0.1
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.5.0
  provider: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  cryptography: ^2.7.0
  cryptography_flutter: ^2.3.2
  flutter_lints: ^5.0.0
  characters: ^1.4.1
  material_color_utilities: ^0.13.0
  meta: ^1.17.0
  lints: ^6.0.0
  test_api: ^0.7.7

flutter:
  uses-material-design: true
 
